import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {HeroUIProvider} from "@heroui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dcluttr",
  description: "Generated by create next app",
  icons: { icon: "/dcluttr_logo.jpeg" }, // Metadata-based favicon setup
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          {/* LEFT NAVBAR */}
          <aside className="w-[13%] md:w-[8%] lg:w-[13%]">
            <Navbar />
          </aside>
          
          {/* RIGHT CONTENT AREA */}
          <main className="w-[87%] md:w-[92%] lg:w-[87%] bg-white flex flex-col">
            {/* <Header /> */}
            {children}
            {/* <Analytics /> */}
          </main>
        </div>
      </body>
    </html>
  );
}
