import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {HeroUIProvider} from "@heroui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dcluttr",
  description: "Generated by create next app",
  icons: { icon: "/dcluttr_logo.jpeg" },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex h-screen overflow-hidden">
          {/* Fixed LEFT NAVBAR */}
          <aside className="fixed h-full w-[18%]">
            <Navbar />
          </aside>
          
          {/* Scrollable RIGHT CONTENT AREA */}
          <main className="ml-[18%] w-[82%] bg-white flex flex-col overflow-y-auto h-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}